"""
Django settings for simpleCRM project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-8h8mq3b$2s7yhp0w)y@u%h1^7b@_5)^^bmhfuhh9e87*^t%0w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',                     # добавляем пакет для регистрации пользователей
    'crm',
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'simpleCRM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simpleCRM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# язык сайта по умолчанию, если не удалось определить язык другими способами
LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# указываем, где лежат файлы перевода
LOCALE_PATHS = (
     os.path.join(BASE_DIR, 'locale'),
)

# список доступных языков
LANGUAGES = (
    ('ru', 'Russian'),
    ('en', 'English'),
)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# Список из возможных абсолютных путей
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# URL относительно корня как будут показаны статические файла ( иконки, картинки, CSS )
STATIC_URL = '/static/'

# Абсолютный путь к загружаемым пользователем файлам
MEDIA_ROOT = os.path.join( BASE_DIR, 'media')
# Сылка относительно корня, как будут показаны загружаемые пользователем файлы
MEDIA_URL = '/media/'

REGISTRATION_OPEN = True        # Если равно True, то пользователи могут регистрироваться
ACCOUNT_ACTIVATION_DAYS = 7     # время в течении которого можно активировать аккаунт;
                                # в качестве примера выбрано 7 дней или одна неделя, но Вы можете указать другое значение.
REGISTRATION_AUTO_LOGIN = True  # Если равно  True, то пользователь будет автоматически входить в систему.
LOGIN_REDIRECT_URL = '/crm/'    # Страница, на которую будут попадать пользователи, после успешного входа в систему.
LOGIN_URL = '/crm/login/'       # Страница, на которую перенаправляются пользователи, если они не вошли в систему и
                                # пытаются получить доступ к страницам, которые требуют аутентификации

# http://djbook.ru/forum/topic/220/
SITE_ID = 1

#localhost с запуском тестового SMTP сервера
#EMAIL_HOST = 'localhost'
#EMAIL_PORT = 1025

# gmail.com
#EMAIL_HOST          = 'smtp.gmail.com'
#EMAIL_PORT          = 587
#EMAIL_HOST_USER     = "alex.abakumov@gmail.com"
#EMAIL_HOST_PASSWORD = "otchenash"
#EMAIL_USE_TLS       = True

# yandex.ru
EMAIL_HOST          = 'smtp.yandex.ru'
EMAIL_PORT          = 465
EMAIL_HOST_USER     = "alex-abakumov@yandex.ru"
EMAIL_HOST_PASSWORD = "eravnomc2eravnomc2"
EMAIL_USE_SSL       = True


# Добавьте ещё две следующие строчки для отправки писем (трейсбека) админам при возникновении ошибок на сайте:
# Яндекс и mail без указания SERVER_EMAIL такого же как адрес пользователя при подключении к SMPT серверу,
#  т.е. EMAIL_HOST_USER, не будет посылать письма об ошибках.

SERVER_EMAIL        = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

# Тест на отправку писем
#from django.core.mail import send_mail
#send_mail('Тема', 'Тело письма', EMAIL_HOST_USER, ['alex.abakumov@gmail.com'])