# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 10:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть в формате: '+999999999. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('mobile_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть в формате: '+999999999. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Мобильный телефон')),
                ('avatar', models.ImageField(blank=True, upload_to='crm/', verbose_name='Фотография')),
                ('first_name', models.CharField(default='Иванов', help_text='Фамилия', max_length=30, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_address', models.EmailField(blank=True, max_length=80, verbose_name='Эл.почта')),
                ('brith_data', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('E', 'First contact'), ('D', 'Decision making'), ('H', 'Harmonization of contract'), ('S', 'The contract is signed'), ('P', 'Checkout paid'), ('E', 'Contract executed successfully'), ('A', 'DEAD DEAL')], max_length=1)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Deal')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть в формате: '+999999999. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('mobile_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть в формате: '+999999999. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Мобильный телефон')),
                ('avatar', models.ImageField(blank=True, upload_to='crm/', verbose_name='Фотография')),
                ('division', models.CharField(blank=True, max_length=50, verbose_name='Подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Менеджер по продажам',
                'verbose_name_plural': 'Менеджеры по продажам',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Email', 'Email'), ('Phone call', 'Телефонный звонок'), ('Other', 'Other')], max_length=1, verbose_name='Действие')),
                ('action_description', models.TextField(verbose_name='Комментарий')),
                ('data_time', models.DateTimeField(verbose_name='Дата и время')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SalesPerson', verbose_name='Менеджер')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SalesPerson'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SalesPerson'),
        ),
    ]
