# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 13:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, upload_to='crm/media/')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_address', models.EmailField(max_length=80)),
                ('brith_data', models.DateField()),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='sales_person',
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='crm/media/'),
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SalesPerson'),
        ),
    ]
