# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160906_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
