# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20160906_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='division',
            field=models.CharField(blank=True, max_length=50, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='dsasds'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(verbose_name='sdsadadasdasd'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='dsasds'),
        ),
    ]
